meta_product_name: "My People My Community"
meta_title: "My People My Community - Skill Share for Social Change"
meta_description: "A social network application that focuses on connecting
philanthropic entities with individuals and communities in need for social development."
meta_image: "ring-logo.png"
